[profile.default]
solc = '0.8.17'
src = 'src'
test = 'src/test'
out = 'out'
libs = ['lib']
fuzz_runs = 1000
optimizer_runs = 10_000

[profile.ci.fuzz]
runs = 10_000

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = true
int_types = 'long'
quote_style = 'double'
number_underscore = 'thousands'
multiline_func_header = 'all'
